### ISSUE TITLE
Checking For Bugs

### ISSUE THREAD

**Issue by IndraA3** [minikopi/sekolah#151]
- [x] superadmin => Sekolah -> tambah sekolah -> (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'school_id' in 'where clause' (Connection: mysql, SQL: select * from `schools` where `school_id` is null and `schools`.`deleted_at` is null))
- [x] superadmin => Sekolah -> tambah sekolah -> action tidak ada (blank)
- [x] #163
- [x] superadmin => Sekolah -> edit sekolah -> (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'school_id' in 'where clause' (Connection: mysql, SQL: select * from `schools` where `school_id` is null and `schools`.`deleted_at` is null))
- [x] #155
- [x] superadmin => keuangan -> wallet -> "Unhandled match case false" saat buat dompet baru dengan opsi bos
- [x] #153
- [x]  superadmin => transaksi -> edit pengeluaran biaya -> error "Nomor Pengeluaran wajib diisi. "
- [x] superadmin => transaksi -> tambah detail pengeluaran biaya -> "Unsupported operand types: App\Models\Wallet - int"
- [x] #160
- [x] keuangan -> persetujuan biaya -> Persetujuan Biaya tambahkan field status

**Comment by backend-sempoa** [comment]
Selesai semuanya. Mari kita tutup sesi bug kali ini dengan mengucapkan "Alhamdulillah".
