### ISSUE TITLE
Bug 05/06/2023

### ISSUE THREAD

**Issue by nekrophantom123** [minikopi/sekolah#220]
- [x] expense tambah kolom status Sudah Direalisasikan (dipakai setelah di approved expensenya) perlu ngirim bukti jika status sudah direalisasikan
- [x] Laporan Tuition penempatan kolom sisa tagihan, total tagihan dan tagihannya
- [x] Menampilkan kelas pada Laporan Siswa

**Comment by backend-sempoa** [comment]
ini siapa mau ngerjain apa nih? hehehe.

@nekrophantom123 @jamalul-insan
