### ISSUE TITLE
Dear, Jamal

### ISSUE THREAD

**Issue by backend-sempoa** [minikopi/sekolah#229]
- [x] Menampilkan tahun ajaran pada detail wali kelas

![image](https://github.com/minikopi/sekolah/assets/100393465/d60f571a-5568-4eee-88ef-21793a1c1002)

- [x] Opsi "ubah" di *Penetapan Wali Kelas* seperti membingungkan karena gak tau asal data atau data apa yang berubah. mungkin kalau bisa dijelaskan, kita biarin. kalau bikin bingung, kita takedown aja. dan mungkin bisa diganti dengan hapus. jadi, ketika pilih hapus, pilihannya adalah kelas yang terdaftar atas nama dia. kelas yg dipilih akan terhapus. gimana?

**Comment by jamalul-insan** [comment]
![image](https://github.com/minikopi/sekolah/assets/101683243/1f6bd363-45ad-43cd-bec6-91a42189c668)

sory gk liat ini beberapa hari

**Comment by jamalul-insan** [comment]
![image](https://github.com/minikopi/sekolah/assets/101683243/0a84f905-29bf-4b23-8a6a-78f347fc5f3a)

**Comment by backend-sempoa** [comment]
udah di-push, @jamalul-insan ?
