### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by backend-sempoa** [minikopi/sekolah#251]
Rekomendasi: Pak Ivan pada 14 Juni 2023

- [x] Ubah urutan

> Urutannya: Tahun Akademik > Tingkatan > Ruang Kelas | Data Staff / Guru > Data Siswa | Rombongan Belajar (ganti jadi Penetapan Kelas) > Rombongan Guru / Staff (ganti jadi wali kelas)
Catatan: | adalah separator

- [x] Label Tipe Biaya ganti jadi Tipe Uang Sekolah

Semangat @nekrophantom123

**Comment by nekrophantom123** [comment]
cape pak wkwkwkww

**Comment by nekrophantom123** [comment]
itu separatornya mo di namain apa aja ? @backend-sempoa

**Comment by backend-sempoa** [comment]
1. Data Master
2. Personalia
3. Data Kelas
