### ISSUE TITLE
Pemilihan Sekolah Ketika login Sebagai Staff Sekolah :bulb: 

### ISSUE THREAD

**Issue by jamalul-insan** [minikopi/sekolah#39]
![image](https://user-images.githubusercontent.com/101683243/228108875-ebeb8d61-17cb-4957-986d-2e7dad8ddb1b.png)

ini  dihilangkan aja ya klau dia login sebagai staff sekolah

@AaEzha 
@nekrophantom123

**Comment by backend-sempoa** [comment]
yes, ini juga berlaku untuk semuanya sih.

setelah PR #40 , untuk nilai school_id bisa didapatkan dengan cara `session('school_id')` di controllernya.
