### ISSUE TITLE
Notre Dame Meeting Concern

### ISSUE THREAD

**Issue by diarmp** [minikopi/sekolah#47]
per tanggal 28 Maret 2023 terdapat 3 concern dari Notre Dame :

1. Issue pembayaran SPP full di muka
   
   Pada case notre dame ada pembayaran SPP full 1 tahun di awal, sehingga orang tua tidak di kirimi invoice. namun secara system pengakuan uang pembayaran nya di buat menjadi 12 bulan ( 1 tahun ajaran ). sehingga di minta untuk pembuatan penanda siswa yang sudah membayar 1 tahun full, sehingga saat pembuatan tagihan bulanan akan secara otomatis di lunaskan secara system

2.  Issue Tunggakan SPP

     Pada case notre dame ada orang tua murid yang membayar kurang dari nominal yang sudah di sepakatin dengan sekolah. sehingga di minta untuk setiap tunggakan uang sekolah yang belum di bayar akan di akumulasi di ke bulan berikut nya.

3. Issue system denda telat pembayaran SPP

    Pada system notre dame yang sudah berjalan, ada sebuah system denda dengan mekasime :
    - Pembayaran di atas tanggal 14 dan di bawah tanggal 28 pada bulan yang sedang berjalan, akan di kenakan denda sebesar Rp. 25.000,-
    - Pembayaran di atas tanggal 28 pada bulan berjalan sampai dengan tanggal 14 bulan berikut nya, akan di kenakan tambahan denda lagi sebesar Rp. 25.000,-
    - Pembayaran di atas tanggal 14 bulan berikut nya dan di bawah tanggal 28 pada bulan berikut nya, akan di kenakan denda tambahan lagi sebesar Rp. 25.000,-

Jika ada pertanyaan atau ada yang kurang jelas dapat di tanyakan langsung kepada saya.

Regard's

Diar J. Suma

**Comment by backend-sempoa** [comment]
Karena belum ada kejelasan mengenai ini, jadi ditutup dulu, yaa..
