### ISSUE TITLE
Grade

### ISSUE THREAD

**Issue by backend-sempoa** [minikopi/sekolah#79]
- [x] Masih bisa duplikat data. Seharusnya tidak boleh ada duplikat data dalam 1 sekolah.
![image](https://user-images.githubusercontent.com/100393465/231039167-497796d8-c888-4dfd-9ccc-ee7af50723cd.png)

**Comment by backend-sempoa** [comment]
@nekrophantom123 ketika ngedit tanpa melakukan perubahan, tetap kena notif unique

![image](https://user-images.githubusercontent.com/100393465/231422451-9afe1ae4-51fd-4784-9d18-0785d867658b.png)

**Comment by nekrophantom123** [comment]
#89
