### ISSUE TITLE
Bug Transaction

### ISSUE THREAD

**Issue by jamalul-insan** [minikopi/sekolah#91]
https://flareapp.io/share/x7X3rEpP#F61

![image](https://user-images.githubusercontent.com/101683243/231678024-a44bbaa5-02e5-427e-bd89-68c4940773e6.png)

**Comment by jamalul-insan** [comment]
![image](https://user-images.githubusercontent.com/101683243/231679654-d8a1710f-f9a7-4356-8329-6c98a1ede179.png)

**Comment by backend-sempoa** [comment]
gimana reproduce-nya? kondisinya gimana sampai bisa muncul seperti itu? @jamalul-insan

**Comment by jamalul-insan** [comment]
kondisinya dia blm ada di classroom

**Comment by backend-sempoa** [comment]
kok di gue muncul aja ya meski belum ada kelas

![image](https://user-images.githubusercontent.com/100393465/231690326-47530b61-77bf-4063-babc-4a36e43cbe14.png)

baik-baik juga meski belum ada tahun ajaran, belum ada tuition

![image](https://user-images.githubusercontent.com/100393465/231690483-804e86f1-8a9e-414b-8f33-72893ca97cb9.png)

udah coba `migrate` dan `sync` kan?

**Comment by jamalul-insan** [comment]
Nampil Tetap coba di simpan

**Comment by backend-sempoa** [comment]
ya gak bisa disimpan kalau belum ada tuition-nya.

kalau udah ada tuition, berarti udah ada semuanya.

**Comment by backend-sempoa** [comment]
berarti masalahnya karena belum ada kelas

**Comment by backend-sempoa** [comment]
udah gue fix ya @jamalul-insan di #96
