### ISSUE TITLE
Transaksi Partial 

### ISSUE THREAD

**Issue by jamalul-insan** [minikopi/sekolah#98]
jika pembayaran spp Rp. 1 jt dengan status partial

pembayaran pertama 500 rb
pembayaran kedua 510 rb
------------------------------------+
jadi 10010000
kelebihan 10000

colek
@AaEzha

**Comment by backend-sempoa** [comment]
Iya gpp lah kalau bayar lebih, yg penting jangan bayar kurang tapi dianggap lunas. wkwkwkw.

**Comment by backend-sempoa** [comment]
yowis tak betulin dulu biar gak bisa lebih
